# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  # Используем образ Ubuntu 18.04
  config.vm.box = "ubuntu/bionic64"
  
  # Прокси-настройки, если необходимо
  # config.proxy.http     = "http://proxy.example.com:80/"
  # config.proxy.https    = "http://proxy.example.com:80/"
  
  # Процесс установки пакетов и настройки
  config.vm.provision "shell", inline: <<-SHELL
    # Обновляем список пакетов и устанавливаем базовые утилиты
    sudo apt-get update
    sudo apt-get install -y python3 python3-pip
    
    # Устанавливаем необходимые Python библиотеки
    sudo pip3 install psycopg2 Django
  SHELL
  
  # Копируем файл на файловую систему виртуальной машины
  config.vm.provision "file", source: "./path/to/your/local/file.txt", destination: "/home/vagrant/file.txt"
  
  # Настройки сети и прочие опции, если необходимо
  
end
